name: Build LaTeX and Upload PDF to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: actions/setup-tex@v1
        with:
          distribution: 'texlive-full' # 或者选择更小的发行版，例如 'texlive-basic'，如果你的项目依赖较少

      - name: Compile LaTeX document
        run: |
          #cd your_latex_directory # 将 'your_latex_directory' 替换为你的 LaTeX 文件所在的目录，如果文件在根目录下则不需要这一行
          latexmk -pdf note.tex # 将 'main.tex' 替换为你的主 LaTeX 文件名
          # 如果 latexmk 不可用或者你需要更复杂的编译流程，可以使用以下命令：
          # pdflatex main.tex
          # bibtex main.aux # 如果使用了 bibtex
          # pdflatex main.tex
          # pdflatex main.tex

      - name: Find PDF file
        id: find_pdf
        run: |
          #cd your_latex_directory # 同样替换为你的 LaTeX 文件目录
          PDF_FILE=$(find . -name "*.pdf" -print -quit)
          echo "PDF_FILE=$PDF_FILE" >> "$GITHUB_OUTPUT"

      - name: Upload PDF to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.find_pdf.outputs.PDF_FILE }}
          asset_name: note.pdf # 你可以自定义上传到 release 中的文件名
          asset_content_type: application/pdf