name: Build LaTeX and Upload PDF to Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: note.tex

      - name: Install CJK language support (including fandol fonts)
        run: |
          sudo apt-get update
          sudo apt-get install texlive-lang-cjk

      - name: List files before compilation
        run: |
          ls -R

      - name: Compile LaTeX document
        run: |
          latexmk -pdf note.tex

      - name: List files after compilation
        run: |
          ls -R

      - name: Find PDF file
        id: find_pdf
        run: |
          PDF_FILE=$(find . -name "*.pdf" -print -quit)
          echo "PDF_FILE=$PDF_FILE" >> "$GITHUB_OUTPUT"
          echo "Found PDF file: $PDF_FILE"

      - name: Upload PDF to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.find_pdf.outputs.PDF_FILE }}
          asset_name: output.pdf
          asset_content_type: application/pdf